server {
    listen 80;
    server_name marmoles.sistemataup.online;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name marmoles.sistemataup.online;

    ssl_certificate /etc/letsencrypt/live/marmoles.sistemataup.online/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/marmoles.sistemataup.online/privkey.pem;

    resolver 127.0.0.11 valid=10s ipv6=off;
    resolver_timeout 5s;

    # Frontend
    location / {
        set $marmoles_frontend_upstream http://marmoles_frontend:5120;
        proxy_pass $marmoles_frontend_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Backend API
    location /api/ {
        set $marmoles_backend_upstream http://marmoles_backend:8000;
        proxy_pass $marmoles_backend_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Backend Docs (Optional but good for debug)
    location /docs {
        set $marmoles_backend_upstream http://marmoles_backend:8000;
        proxy_pass $marmoles_backend_upstream;
        proxy_set_header Host $host;
    }
    location /openapi.json {
        set $marmoles_backend_upstream http://marmoles_backend:8000;
        proxy_pass $marmoles_backend_upstream;
        proxy_set_header Host $host;
    }
}
