from alembic import op
import sqlalchemy as sa

revision = 'f2842c5cf4c2'
down_revision = 'manual_full_update_04'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # piezas_trabajo: nombre exists, tipo missing
    # op.add_column('piezas_trabajo', sa.Column('nombre', sa.String(length=255), nullable=True))
    op.add_column('piezas_trabajo', sa.Column('tipo', sa.String(length=32), nullable=False, server_default='pieza'))
    
    # placas: all missing
    op.add_column('placas', sa.Column('espesor', sa.Integer(), nullable=True))
    op.add_column('placas', sa.Column('codigo', sa.String(length=64), nullable=True))
    op.add_column('placas', sa.Column('plano_tecnico_id', sa.String(length=36), nullable=True))
    op.add_column('placas', sa.Column('ubicacion', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_placas_codigo'), 'placas', ['codigo'], unique=False)
    # op.create_index(op.f('ix_placas_lote_id'), 'placas', ['lote_id'], unique=False)
    op.create_index(op.f('ix_placas_plano_tecnico_id'), 'placas', ['plano_tecnico_id'], unique=False)
    
    # retazos: all exist
    # op.add_column('retazos', sa.Column('lote_id', sa.String(length=36), nullable=True))
    # op.add_column('retazos', sa.Column('espesor', sa.Integer(), nullable=True))
    # op.add_column('retazos', sa.Column('ubicacion', sa.String(length=64), nullable=True))
    # op.create_index(op.f('ix_retazos_lote_id'), 'retazos', ['lote_id'], unique=False)
    
    # trabajos: all exist
    # op.add_column('trabajos', sa.Column('fecha_visita_sugerida', sa.String(length=64), nullable=True))
    # ...
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('trabajos', ...)
    
    op.drop_index(op.f('ix_placas_plano_tecnico_id'), table_name='placas')
    op.drop_index(op.f('ix_placas_lote_id'), table_name='placas')
    op.drop_index(op.f('ix_placas_codigo'), table_name='placas')
    op.drop_column('placas', 'ubicacion')
    op.drop_column('placas', 'plano_tecnico_id')
    op.drop_column('placas', 'codigo')
    op.drop_column('placas', 'espesor')
    op.drop_column('piezas_trabajo', 'tipo')
    # op.drop_column('piezas_trabajo', 'nombre')
    # ### end Alembic commands ###
