from alembic import op
import sqlalchemy as sa

revision = 'fcf29546dfb3'
down_revision = '0001_initial'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actividades',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('oportunidad_id', sa.String(length=36), nullable=False),
    sa.Column('tipo', sa.String(length=64), nullable=False),
    sa.Column('nota', sa.String(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actividades_oportunidad_id'), 'actividades', ['oportunidad_id'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compras',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('proveedor', sa.String(length=255), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('fecha', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compras_material_id'), 'compras', ['material_id'], unique=False)
    op.create_table('inventario_movimientos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tipo', sa.String(length=16), nullable=False),
    sa.Column('proveedor', sa.String(length=255), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('fecha', sa.String(length=64), nullable=True),
    sa.Column('estado', sa.String(length=16), nullable=False),
    sa.Column('retazo_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventario_movimientos_material_id'), 'inventario_movimientos', ['material_id'], unique=False)
    op.create_index(op.f('ix_inventario_movimientos_retazo_id'), 'inventario_movimientos', ['retazo_id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materiales',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('precio_m2', sa.Float(), nullable=False),
    sa.Column('espesor_mm', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=64), nullable=True),
    sa.Column('ancho_m', sa.Float(), nullable=True),
    sa.Column('largo_m', sa.Float(), nullable=True),
    sa.Column('stock_actual', sa.Float(), nullable=False),
    sa.Column('unidad', sa.String(length=16), nullable=False),
    sa.Column('stock_minimo', sa.Float(), nullable=False),
    sa.Column('ultima_actualizacion', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oportunidades',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=True),
    sa.Column('cliente_id', sa.String(length=36), nullable=True),
    sa.Column('estado', sa.String(length=32), nullable=False),
    sa.Column('monto_estimado', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oportunidades_cliente_id'), 'oportunidades', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_oportunidades_lead_id'), 'oportunidades', ['lead_id'], unique=False)
    op.create_table('piezas_trabajo',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trabajo_id', sa.String(length=36), nullable=False),
    sa.Column('w', sa.Integer(), nullable=False),
    sa.Column('h', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_piezas_trabajo_trabajo_id'), 'piezas_trabajo', ['trabajo_id'], unique=False)
    op.create_table('placas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('ancho', sa.Integer(), nullable=False),
    sa.Column('largo', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=32), nullable=False),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('reservado_por', sa.String(length=36), nullable=True),
    sa.Column('reservado_hasta', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_placas_material_id'), 'placas', ['material_id'], unique=False)
    op.create_table('planos_cliente_material',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cliente_id', sa.String(length=36), nullable=False),
    sa.Column('material', sa.String(length=255), nullable=False),
    sa.Column('imagen', sa.Text(), nullable=True),
    sa.Column('aprobado', sa.Boolean(), nullable=False),
    sa.Column('firmado_por', sa.String(length=255), nullable=True),
    sa.Column('medidas', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planos_cliente_material_cliente_id'), 'planos_cliente_material', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_planos_cliente_material_material'), 'planos_cliente_material', ['material'], unique=False)
    op.create_table('presupuesto_lineas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('presupuesto_id', sa.String(length=36), nullable=False),
    sa.Column('material', sa.String(length=255), nullable=False),
    sa.Column('metros_cuadrados', sa.Float(), nullable=False),
    sa.Column('medidas', sa.String(length=255), nullable=True),
    sa.Column('precio_unitario', sa.Float(), nullable=True),
    sa.Column('condiciones', sa.String(length=255), nullable=True),
    sa.Column('cortes_especiales', sa.Boolean(), nullable=False),
    sa.Column('agujeros', sa.Integer(), nullable=True),
    sa.Column('recargo_extra', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presupuesto_lineas_presupuesto_id'), 'presupuesto_lineas', ['presupuesto_id'], unique=False)
    op.create_table('presupuesto_meta',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('presupuesto_id', sa.String(length=36), nullable=False),
    sa.Column('data_json', sa.String(length=8192), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presupuesto_meta_presupuesto_id'), 'presupuesto_meta', ['presupuesto_id'], unique=False)
    op.create_table('presupuestos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cliente_id', sa.String(length=36), nullable=True),
    sa.Column('observaciones', sa.String(length=1024), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presupuestos_cliente_id'), 'presupuestos', ['cliente_id'], unique=False)
    op.create_table('proveedores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('contacto', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retazos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('ancho', sa.Integer(), nullable=False),
    sa.Column('largo', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=32), nullable=False),
    sa.Column('en_venta', sa.Boolean(), nullable=False),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retazos_material_id'), 'retazos', ['material_id'], unique=False)
    op.create_table('trabajos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cliente', sa.String(length=255), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('presupuesto_id', sa.String(length=36), nullable=True),
    sa.Column('estado', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trabajos_material_id'), 'trabajos', ['material_id'], unique=False)
    op.create_index(op.f('ix_trabajos_presupuesto_id'), 'trabajos', ['presupuesto_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trabajos_presupuesto_id'), table_name='trabajos')
    op.drop_index(op.f('ix_trabajos_material_id'), table_name='trabajos')
    op.drop_table('trabajos')
    op.drop_index(op.f('ix_retazos_material_id'), table_name='retazos')
    op.drop_table('retazos')
    op.drop_table('proveedores')
    op.drop_index(op.f('ix_presupuestos_cliente_id'), table_name='presupuestos')
    op.drop_table('presupuestos')
    op.drop_index(op.f('ix_presupuesto_meta_presupuesto_id'), table_name='presupuesto_meta')
    op.drop_table('presupuesto_meta')
    op.drop_index(op.f('ix_presupuesto_lineas_presupuesto_id'), table_name='presupuesto_lineas')
    op.drop_table('presupuesto_lineas')
    op.drop_index(op.f('ix_planos_cliente_material_material'), table_name='planos_cliente_material')
    op.drop_index(op.f('ix_planos_cliente_material_cliente_id'), table_name='planos_cliente_material')
    op.drop_table('planos_cliente_material')
    op.drop_index(op.f('ix_placas_material_id'), table_name='placas')
    op.drop_table('placas')
    op.drop_index(op.f('ix_piezas_trabajo_trabajo_id'), table_name='piezas_trabajo')
    op.drop_table('piezas_trabajo')
    op.drop_index(op.f('ix_oportunidades_lead_id'), table_name='oportunidades')
    op.drop_index(op.f('ix_oportunidades_cliente_id'), table_name='oportunidades')
    op.drop_table('oportunidades')
    op.drop_table('materiales')
    op.drop_table('leads')
    op.drop_index(op.f('ix_inventario_movimientos_retazo_id'), table_name='inventario_movimientos')
    op.drop_index(op.f('ix_inventario_movimientos_material_id'), table_name='inventario_movimientos')
    op.drop_table('inventario_movimientos')
    op.drop_index(op.f('ix_compras_material_id'), table_name='compras')
    op.drop_table('compras')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_actividades_oportunidad_id'), table_name='actividades')
    op.drop_table('actividades')
    # ### end Alembic commands ###
